# Pre-commit hooks configuration for OpenTranscribe
# See https://pre-commit.com for more information

repos:
  # General pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: [--unsafe]  # Allow custom YAML tags in docker-compose
      - id: check-json
      - id: check-added-large-files
        args: [--maxkb=10240]  # 10MB max file size
      - id: check-merge-conflict
      - id: check-toml
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable

  # Python formatting and linting with Ruff (replaces Black, isort, flake8)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.2
    hooks:
      - id: ruff
        args: [--fix, --show-fixes]
        files: ^backend/
      - id: ruff-format
        files: ^backend/

  # Python type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        files: ^backend/
        additional_dependencies:
          - types-requests
          - types-python-dateutil
          - types-pyyaml
          - types-redis
        args: [--ignore-missing-imports, --check-untyped-defs]

  # Frontend formatting with Prettier
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        files: ^frontend/
        types_or: [javascript, jsx, ts, tsx, json, yaml, html, css, scss, markdown]
        args: [--write, --ignore-unknown]

  # Dockerfile linting
  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint-docker
        name: Lint Dockerfiles
        files: Dockerfile.*
        entry: hadolint
        language: system

  # Secret detection
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.1
    hooks:
      - id: gitleaks
        args: [--verbose, --no-banner]

  # Python security linting
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.7
    hooks:
      - id: bandit
        files: ^backend/
        args: [-c, pyproject.toml, -r, backend/]
        additional_dependencies: ["bandit[toml]"]

  # Shell script linting
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.6
    hooks:
      - id: shellcheck
        args: [--severity=warning]

  # Commit message linting (optional)
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.0.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [--force-scope]

# Configuration for specific hooks
default_stages: [commit]
fail_fast: false
