<script lang="ts">
  import type { SummaryData, MajorTopic } from '$lib/types/summary';
  import TopicsList from './TopicsList.svelte';

  export let summary: SummaryData;
  // fileName prop removed - not used internally
  export let searchQuery: string = '';
  export let currentMatchIndex: number = 0;
  
  // Create a function that generates all matches with proper indexing
  function highlightWithGlobalIndex(text: string, globalMatchIndex: { count: number }): string {
    if (!searchQuery || !text) return text;
    
    const escapedQuery = searchQuery.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    const regex = new RegExp(`(${escapedQuery})`, 'gi');
    
    return text.replace(regex, (match) => {
      const isCurrentMatch = globalMatchIndex.count === currentMatchIndex;
      const thisMatchIndex = globalMatchIndex.count;
      globalMatchIndex.count++;
      
      if (isCurrentMatch) {
        return `<mark class="current-match" data-match-index="${thisMatchIndex}">${match}</mark>`;
      } else {
        return `<mark class="search-match" data-match-index="${thisMatchIndex}">${match}</mark>`;
      }
    });
  }
  
  // Reactive function to generate highlighted content
  function getHighlightedContent() {
    if (!searchQuery || !summary) return null;
    
    const globalIndex = { count: 0 };
    
    return {
      bluf: highlightWithGlobalIndex(summary.bluf || '', globalIndex),
      briefSummary: highlightWithGlobalIndex(summary.brief_summary || '', globalIndex),
      keyDecisions: (summary.key_decisions || []).map(decision => highlightWithGlobalIndex(decision || '', globalIndex)),
      followUpItems: (summary.follow_up_items || []).map(item => highlightWithGlobalIndex(item || '', globalIndex)),
      majorTopics: (summary.major_topics || []).map(topic => ({
        ...topic,
        topic: highlightWithGlobalIndex(topic.topic || '', globalIndex),
        key_points: (topic.key_points || []).map(point => highlightWithGlobalIndex(point || '', globalIndex)),
        participants: (topic.participants || []).map(p => highlightWithGlobalIndex(p || '', globalIndex))
      }))
    };
  }
  
  let highlightedContent: any = null;
  
  // Reactive statement that triggers when searchQuery OR currentMatchIndex changes
  $: {
    // Force reactivity by referencing both variables
    const query = searchQuery;
    const matchIndex = currentMatchIndex;
    
    if (query && summary) {
      highlightedContent = getHighlightedContent();
    } else {
      highlightedContent = null;
    }
  }
</script>

<div class="summary-content">
  <!-- BLUF Section -->
  <section class="bluf-section">
    <h3 class="section-title">Executive Summary (BLUF)</h3>
    <div class="bluf-content">
      {@html highlightedContent?.bluf || summary.bluf}
    </div>
  </section>

  <!-- Brief Summary Section -->
  <section class="brief-summary-section">
    <h3 class="section-title">Brief Summary</h3>
    <div class="brief-summary-content">
      {@html highlightedContent?.briefSummary || summary.brief_summary}
    </div>
  </section>

  <!-- Major Topics -->
  {#if summary.major_topics && summary.major_topics.length > 0}
    <TopicsList 
      topics={highlightedContent?.majorTopics || summary.major_topics} 
      {searchQuery} 
    />
  {/if}

  <!-- Key Decisions -->
  {#if summary.key_decisions && summary.key_decisions.length > 0}
    <section class="key-decisions-section">
      <h3 class="section-title">Key Decisions</h3>
      <div class="key-decisions-list">
        {#each (highlightedContent?.keyDecisions || summary.key_decisions) as decision}
          <div class="key-decision-item">
            <div class="decision-bullet">✓</div>
            <div class="decision-text">{@html decision}</div>
          </div>
        {/each}
      </div>
    </section>
  {/if}

  <!-- Follow-up Items -->
  {#if summary.follow_up_items && summary.follow_up_items.length > 0}
    <section class="follow-up-section">
      <h3 class="section-title">Follow-up Items</h3>
      <div class="follow-up-list">
        {#each (highlightedContent?.followUpItems || summary.follow_up_items) as item}
          <div class="follow-up-item">
            <div class="follow-up-bullet">→</div>
            <div class="follow-up-text">{@html item}</div>
          </div>
        {/each}
      </div>
    </section>
  {/if}

  <!-- AI Disclaimer -->
  <section class="ai-disclaimer-section">
    <div class="ai-disclaimer">
      <p class="disclaimer-text">
        AI-generated summary - please verify important details. 
        {#if summary.metadata}
          Generated by {summary.metadata.provider} ({summary.metadata.model}).
        {/if}
      </p>
    </div>
  </section>
</div>

<style>
  .summary-content {
    padding: 1.5rem;
    max-height: calc(100vh - 200px);
    overflow-y: auto;
  }

  .section-title {
    font-size: 1.25rem;
    font-weight: 600;
    margin-bottom: 0.75rem;
    color: var(--text-primary);
    border-bottom: 2px solid var(--border-color);
    padding-bottom: 0.5rem;
  }

  .bluf-section, .brief-summary-section {
    margin-bottom: 2rem;
  }

  /* Add consistent spacing between all sections */
  section {
    margin-bottom: 2rem;
  }

  section:last-child {
    margin-bottom: 1rem;
  }

  .bluf-content, .brief-summary-content {
    line-height: 1.6;
    color: var(--text-secondary);
  }


  .key-decisions-list, .follow-up-list {
    display: flex;
    flex-direction: column;
    gap: 0.75rem;
  }

  .key-decision-item, .follow-up-item {
    display: flex;
    align-items: flex-start;
    gap: 0.75rem;
  }

  .decision-bullet, .follow-up-bullet {
    color: var(--success-color);
    font-weight: 600;
    margin-top: 0.1rem;
  }

  .decision-text, .follow-up-text {
    flex: 1;
    line-height: 1.5;
  }

  .ai-disclaimer-section {
    margin-top: 2rem;
    padding-top: 1rem;
    border-top: 1px solid var(--border-color);
  }

  .ai-disclaimer {
    text-align: center;
  }

  .disclaimer-text {
    font-size: 0.8rem;
    color: var(--text-muted);
    font-style: italic;
    margin: 0;
    line-height: 1.4;
  }

  /* Search highlighting styles */
  :global(.search-match) {
    background-color: #ffeb3b;
    color: #000;
    padding: 0.1rem 0.2rem;
    border-radius: 3px;
    font-weight: 500;
  }

  :global(.current-match) {
    background-color: #ff9800;
    color: #000;
    padding: 0.1rem 0.2rem;
    border-radius: 3px;
    font-weight: 600;
    box-shadow: 0 0 0 2px rgba(255, 152, 0, 0.3);
  }
</style>