#!/bin/bash
# Generate a .env file for an isolated release-test deployment.
#
# Contract: callers must have set (from the scenario script):
#   TEST_ROOT, TEST_PROJECT_NAME
#   TEST_FRONTEND_PORT, TEST_BACKEND_PORT, TEST_FLOWER_PORT,
#   TEST_POSTGRES_PORT, TEST_REDIS_PORT, TEST_MINIO_PORT,
#   TEST_MINIO_CONSOLE_PORT, TEST_OPENSEARCH_PORT
#
# Secrets: if $TEST_ROOT/../.env.test-secrets exists it is sourced first so
# HUGGINGFACE_TOKEN and optional LLM creds flow through.

set -euo pipefail

et_rand_hex() {
    # 32 random hex chars
    if command -v openssl >/dev/null 2>&1; then
        openssl rand -hex "${1:-32}"
    else
        python3 -c "import secrets; print(secrets.token_hex($1))" "${1:-32}"
    fi
}

et_write_env() {
    local out="$1"
    local postgres_pw minio_pw jwt_secret enc_key redis_pw

    postgres_pw=$(et_rand_hex 16)
    minio_pw=$(et_rand_hex 16)
    jwt_secret=$(et_rand_hex 32)
    enc_key="release-test-$(et_rand_hex 16)"
    redis_pw=$(et_rand_hex 16)

    # Source test secrets if present (HUGGINGFACE_TOKEN, LLM_*, etc.)
    local secrets_file="${OT_RELEASE_TEST_SECRETS:-$TEST_ROOT/../.env.test-secrets}"
    if [[ -f "$secrets_file" ]]; then
        # shellcheck disable=SC1090
        source "$secrets_file"
    fi

    mkdir -p "$(dirname "$out")"
    cat > "$out" <<EOF
# Auto-generated by scripts/release-tests/lib/env-template.sh
# DO NOT EDIT BY HAND — regenerated on every test run.
# Project: ${TEST_PROJECT_NAME}

COMPOSE_PROJECT_NAME=${TEST_PROJECT_NAME}

# ─── Ports (isolated from the live 5173-5180 range) ──────────
FRONTEND_PORT=${TEST_FRONTEND_PORT}
BACKEND_PORT=${TEST_BACKEND_PORT}
FLOWER_PORT=${TEST_FLOWER_PORT}
POSTGRES_PORT=${TEST_POSTGRES_PORT}
REDIS_PORT=${TEST_REDIS_PORT}
MINIO_PORT=${TEST_MINIO_PORT}
MINIO_CONSOLE_PORT=${TEST_MINIO_CONSOLE_PORT}
OPENSEARCH_PORT=${TEST_OPENSEARCH_PORT}

# ─── Credentials (generated per run) ─────────────────────────
POSTGRES_USER=opentranscribe
POSTGRES_PASSWORD=${postgres_pw}
POSTGRES_DB=opentranscribe
MINIO_ROOT_USER=minioadmin
MINIO_ROOT_PASSWORD=${minio_pw}
MINIO_BUCKET=opentranscribe
REDIS_PASSWORD=${redis_pw}
JWT_SECRET_KEY=${jwt_secret}
ENCRYPTION_KEY=${enc_key}

# ─── Model cache (isolated per test run) ─────────────────────
MODEL_CACHE_DIR=${TEST_ROOT}/models

# ─── AI models and hardware (CPU-only by default for safety) ─
WHISPER_MODEL=${WHISPER_MODEL:-large-v3-turbo}
COMPUTE_TYPE=${COMPUTE_TYPE:-int8}
BATCH_SIZE=${BATCH_SIZE:-4}
USE_GPU=${USE_GPU:-false}
CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES:-}

# ─── HuggingFace token (from .env.test-secrets) ──────────────
HUGGINGFACE_TOKEN=${HUGGINGFACE_TOKEN:-}

# ─── LLM (optional, sourced from .env.test-secrets) ──────────
LLM_PROVIDER=${LLM_PROVIDER:-}
VLLM_BASE_URL=${VLLM_BASE_URL:-}
VLLM_API_KEY=${VLLM_API_KEY:-}
VLLM_MODEL_NAME=${VLLM_MODEL_NAME:-}
OPENAI_API_KEY=${OPENAI_API_KEY:-}
OPENAI_MODEL_NAME=${OPENAI_MODEL_NAME:-}

# ─── OpenSearch neural search ────────────────────────────────
OPENSEARCH_NEURAL_SEARCH_ENABLED=true
OPENSEARCH_NEURAL_MODEL=huggingface/sentence-transformers/all-MiniLM-L6-v2

# ─── Skip the live-deploy dev overrides ──────────────────────
# (Neither docker-compose.override.yml nor docker-compose.local.yml is loaded
# in the release-test scripts — they use explicit -f invocations only.)
EOF

    chmod 600 "$out"
    echo "wrote $out"
}
