import type { Plugin } from 'vite';
import { promises as fs } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, resolve } from 'path';

// Static assets that always exist at known paths
const STATIC_ASSETS = [
  '/',
  '/manifest.json',
  '/favicon.ico',
  '/fonts/Poppins-Regular.woff2',
  '/fonts/Poppins-Medium.woff2',
  '/fonts/Poppins-Bold.woff2',
  '/icons/icon-192x192.png',
  '/icons/icon-512x512.png',
  '/icons/icon-180x180.png',
];

export default function serviceWorkerPlugin(): Plugin {
  return {
    name: 'vite-plugin-service-worker',
    apply: 'build',
    async writeBundle(options, bundle) {
      const __filename = fileURLToPath(import.meta.url);
      const __dirname = dirname(__filename);

      const swDest = resolve(__dirname, '../dist/service-worker.js');

      // Ensure the directory exists
      await fs.mkdir(dirname(swDest), { recursive: true });

      // Dynamically discover hashed CSS/JS assets from the build output
      const hashedAssets = Object.keys(bundle)
        .filter((f) => f.endsWith('.css') || f.endsWith('.js'))
        .map((f) => `/${f}`);

      const allAssets = [...STATIC_ASSETS, ...hashedAssets];

      // Use build timestamp for cache busting on deployments
      const buildHash = Date.now().toString(36);
      const cacheName = `transcribe-app-cache-${buildHash}`;

      const content = `// Service Worker - Auto-generated by Vite
// Generated at: ${new Date().toISOString()}
// Cache version: ${buildHash}

const CACHE_NAME = '${cacheName}';
const ASSETS_TO_CACHE = ${JSON.stringify(allAssets, null, 2)};

// Install event - cache all static assets and take over immediately
self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME)
      .then((cache) => cache.addAll(ASSETS_TO_CACHE))
      .then(() => self.skipWaiting())
  );
});

// Activate event - clean up old caches and claim clients
self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((cacheNames) => {
        return Promise.all(
          cacheNames
            .filter((name) => name !== CACHE_NAME)
            .map((name) => caches.delete(name))
        );
      })
      .then(() => self.clients.claim())
  );
});

// Fetch event - serve from cache, falling back to network
self.addEventListener('fetch', (event) => {
  const request = event.request;

  // Skip non-GET requests and chrome-extension URLs
  if (request.method !== 'GET' || request.url.startsWith('chrome-extension://')) {
    return;
  }

  // API requests: always go to network, never cache (contains authenticated data)
  if (request.url.includes('/api/') || request.url.includes('/ws')) {
    return;
  }

  // For static assets, try cache first, then network
  event.respondWith(
    (async () => {
      const cachedResponse = await caches.match(request);
      if (cachedResponse) {
        return cachedResponse;
      }
      try {
        const response = await fetch(request);
        if (!response || response.status !== 200 || response.type !== 'basic') {
          return response;
        }
        const responseToCache = response.clone();
        caches.open(CACHE_NAME)
          .then((cache) => cache.put(request, responseToCache));
        return response;
      } catch (error) {
        console.error('Fetch failed; returning offline page instead.', error);
        return new Response('Network error happened', {
          status: 408,
          headers: { 'Content-Type': 'text/plain' },
        });
      }
    })()
  );
});
`;

      await fs.writeFile(swDest, content, 'utf-8');
      console.log(
        `Service worker generated at: ${swDest} (cache: ${cacheName}, ${hashedAssets.length} hashed assets)`
      );
    },
  };
}
